### ISSUE TITLE
Client error LogSizeLimit

### ISSUE THREAD

**Issue by mscreations** [devopsarr/terraform-provider-radarr#265]
The Radarr api was updated and the radarr_host resource won't apply properly.

Here is the error message I receive:
```╷
│ Error: Client Error
│
│   with radarr_host.radarr,
│   on arrapps.tf line 196, in resource "radarr_host" "radarr":
│  196: resource "radarr_host" "radarr" {
│
│ Unable to update host, got error: 400 Bad Request
│ Details:
│ [
│   {
│     "propertyName": "LogSizeLimit",
│     "errorMessage": "\u0027Log Size Limit\u0027 must be between 1 and 10. You entered 0.",
│     "attemptedValue": 0,
│     "severity": "error",
│     "errorCode": "InclusiveBetweenValidator",
│     "formattedMessageArguments": [],
│     "formattedMessagePlaceholderValues": {
│       "from": 1,
│       "to": 10,
│       "value": 0,
│       "propertyName": "Log Size Limit",
│       "propertyValue": 0
│     }
│   }
│ ]
```

This looks like a new property they added to the API, but it causes the terraform provider to fail because there is no way that I can determine to set that property.

**Comment by Fuochi** [comment]
Hi @mscreations,
I am aware, the API change has already been merged here https://github.com/devopsarr/radarr-go/pull/69. I still have to create a new SDK release, and then a new provider release. And this goes for the other terraform providers as well. I'll try to find time to do that soon.

**Comment by Fuochi** [comment]
Hi @mscreations, could you please check v2.3.0?

**Comment by Fuochi** [comment]
Hi @mscreations, Have you had the chance to look at v2.3.0?

**Comment by beschoenen** [comment]
@Fuochi I can confirm I do not get the error bij @mscreations when updating my `radarr_host` resource.

**Comment by Fuochi** [comment]
great, I'll work on the other providers soon
